name: campuspay
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^17.1.0
  supabase_flutter: ^2.12.2
  dio: ^5.9.2
  flutter_secure_storage: ^10.0.0
  app_links: ^7.0.0
  flutter_local_notifications: ^21.0.0
  equatable: ^2.0.8
  get_it: ^9.2.1
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  crypto: ^3.0.6
  google_fonts: ^6.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:

  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1E3A5F"  # your navy color
  adaptive_icon_foreground: "assets/icons/app_icon.png"

